### ISSUE TITLE
Google drive and mega credentials

### ISSUE THREAD

**Issue by Hapseleg** [AlexCSDev/UniversalDownloaderPlatform#16]
Hi there, thank you for making this repo, its pretty neat :)

I have been trying to figure out how I should generate the credentials needed for your google drive and mega plugin but havent been able to figure it out, is it possible that you could explain it?

-Hapse

**Comment by AlexCSDev** [comment]
https://github.com/AlexCSDev/PatreonDownloader/blob/master/docs/GOOGLEDRIVE.md
https://github.com/AlexCSDev/PatreonDownloader/blob/master/docs/MEGA.md

Google drive one has been reported to be slightly outdated because of changes in google's documentation but it's enough to get a general idea of what you need to do.

**Comment by AlexCSDev** [comment]
Actually you can refer to this for google drive: https://github.com/AlexCSDev/PatreonDownloader/issues/177
